use_frameworks!

target 'Example' do
  platform :ios, '10.0'

  pod "Pastel"
  pod 'Emoji-swift'
  pod 'lottie-ios'
  pod 'Alamofire', '~> 5.4'
  pod 'TelegramStickersImport', :path => '../'

  # In production, you should use:
  # pod 'TelegramStickersImport'

end
